### ISSUE TITLE
your maven repository is dead, bro

### ISSUE THREAD

**Issue by erxson** [EnderSuite/EnderSync#4]
fix it, please
`
[ERROR] Failed to execute goal on project endersync: Could not resolve dependencies for project com.endersuite:endersync:pom:5.0.0: The following artifacts could not be resolved: com.endersuite:packify:jar:1.2.0, com.endersuite:database:jar:1.0.0: com.endersuite:packify:jar:1.2.0 was not found in https://hub.spigotmc.org/nexus/content/repositories/snapshots/ during a previous attempt. This failure was cached in the local repository and resolution is not reattempted until the update interval of spigot-repo has elapsed or updates are forced -> [Help 1]
`

**Comment by MaximilianHeidenreich** [comment]
Hi @erxson , sry for the inconvenience. I am currently not working on the project. That is the reason the repo is down.

If you still want to compile it, just clone:
- https://github.com/EnderSuite/Packify
- https://github.com/EnderSuite/database

Then you need to build/install them with maven which will make them available for EnderSync compilation.
